//===============================================================================
//  seHclData information generated by 13781CFG.EXE (Build 31)
//  (C)SEIKO EPSON CORPORATION 2009. All rights reserved.
//
//  DEVICES   [*ON]     WxHxBPP DESCRIPTION                                      
//  --------------- ----------- -------------------------------------------------
// *Display          320x240x24 Active TFT
// 
//  DIMENSIONS          WxHxBPP STRIDE START   SADDR                             
//  --------------- ----------- ------ ------- ----------------------------------
// *Main Window      320x240x24    960 N/A     00000000h
// *PIP Window         64x64x24    192 160,0   00038400h
// 
//  CLOCKS     FREQ        SOURCE                                                
//  ---------- ----------- ------------------------------------------------------
//  SYSCLK      54.000 MHz PLL
//  PCLK         6.750 MHz SYSCLK/8
//
//  This file INSTANTIATES the segHclInfo structure, and should
//  only be included, one time, by the API's HCL.
//===============================================================================

#include "initdata.h"
#include "registers.h"

seHclData segHclInfo =
{
    "13781 HAL EXE",        // HCL ID string
    "\x00",                 // Configuration description
    "\x00",                 // Parallel LCD1 strings pool
    sizeof(seHclData),      // Sizeof this structure
    0xA0B1,                 // CRC of the rest of structure

    "13781",                // Chip ID
    0x1234,                 // Endian detect (LE=0x1234)
    0,                      // Reserved for alignment

    24000000L,              // CLKI frequency (in Hz)

    {
    0x40,                   
    0x55,                   
    0x55,                   
    0xDF,                   
    0x00,                   
    0x00
    },

    0x00000000,             // Physical base memory address
    0x00060800,             // Physical register address offset
    0x00000000,             // Physical memory address offset

    sefADAPTER_USB,         // Hcl Information flags

    {                       // LCD1 init sequence
        seHCL_LCD_ENDOFTABLE
    },

    {                       // 13781 init registers
        { REG06_RESET,                          0x0100 },
        { REGFLAG_ON_DELAY,                     0x2710 },
        { REG04_POWER_SAVE,                     0x0000 },
        { REG10_PLL_0,                          0x0000 },
        { REG12_PLL_1,                          0x0017 },
        { REG14_PLL_2,                          0x0035 },
        { REG10_PLL_0,                          0x0001 },
        { REGFLAG_DELAY,                        0x09C4 },
        { REG16_INTCLK,                         0x0007 },
        { REG04_POWER_SAVE,                     0x0002 },
        { REG20_PANEL_SET,                      0x004D },
        { REG22_DISP_SET,                       0x0001 },
        { REG24_HDISP,                          0x0028 },
        { REG26_HNDP,                           0x0050 },
        { REG28_VDISP,                          0x00F0 },
        { REG2A_VNDP,                           0x0017 },
        { REG2C_HSW,                            0x0090 },
        { REG2E_HPS,                            0x0010 },
        { REG30_VSW,                            0x0082 },
        { REG32_VPS,                            0x0011 },
        { REG40_MAIN_SET,                       0x0000 },
        { REG42_MAIN_SADDR_0,                   0x0000 },
        { REG44_MAIN_SADDR_1,                   0x0000 },
        { REG50_PIP_SET,                        0x0000 },
        { REG52_PIP_SADDR_0,                    0x8400 },
        { REG54_PIP_SADDR_1,                    0x0003 },
        { REG56_PIP_WIDTH,                      0x0040 },
        { REG58_PIP_HEIGHT,                     0x0040 },
        { REG5A_PIP_XSTART,                     0x00A0 },
        { REG5C_PIP_YSTART,                     0x0000 },
        { REG60_PIP_EN,                         0x0001 },
        { REG62_ALPHA,                          0x0040 },
        { REG64_TRANS,                          0x0000 },
        { REG66_KEY_0,                          0x0000 },
        { REG68_KEY_1,                          0x0000 },
        { REGD0_GPIO_CONFIG,                    0x0001 },
        { REGD2_GPIO_STATUS,                    0x0001 },
        { REGD4_GPIO_PULLDOWN,                  0x0000 },
        { REGFLAG_END_OF_TABLE,                 0x0000 }
    }
};

//#define seHCL_REGSIZE      39
//#define seHCL_LCD1SIZE     1

